import { TheCatchFull, plan07 } from "@/assets";
import { MediaPlayer, TextMask } from "@/components";
import AnimatedText from "@/components/animated-text";

export default function Planetary07() {
	return (
		<div className="w-full padding-y padding-x">
			<div className="flex items-center justify-center flex-col gap-10">
				<MediaPlayer src={TheCatchFull} />
				<div className="">
					<AnimatedText
						text="Meditation on Jupiter"
						className="text-[#2E073F] heading font-semibold papyrus leading-tight"
					/>
				</div>
				<div className="w-full flex items-center gap-10 flex-col">
					<div className="w-full flex items-center justify-center gap-10">
						<div className="flex-1">
							<img
								src={plan07}
								alt="Meditation on Jupiter"
								className="w-full h-full object-cover rounded-t-full"
							/>
						</div>
						<div className="flex-1 flex flex-col gap-5">
							<p className="text-black paragraph font-normal montserrat leading-loose tracking-normal">
								<TextMask>
									{[
										"Planet Jupiter is the true giant of the local solar system; it’s equatorial radius is 11.209 times that of Earth, technically the diameter is 88,846 miles at the equator. It is composed of a rocky core segueing gradually into a gaseous sludge, followed by an atmosphere segregated into several bands at various latitudes; all of which are composed mostly of hydrogen and helium. With a surface temperature ranging between -319° to -162° Fahrenheit humans will not be colonizing there anytime soon, but we may take a stab at some of the larger Galilean Satellites that orbit the planet such as Io, Europa, Ganymede and Calisto.",
									]}
								</TextMask>
							</p>
							<p className="text-black paragraph font-normal montserrat leading-loose tracking-normal">
								<TextMask>
									{[
										"Jupiter’s gravitational pull reaches all the way to the Sun , therefore it does overtly have influence over all other objects in our solar system. Besides the prominent Red Spot, the most spectacular feature of Jupiter is its magnetic field, which is 14 times more powerful than that on Earth.",
									]}
								</TextMask>
							</p>
						</div>
					</div>
					<div className="flex flex-col gap-4">
						<p className="text-black paragraph font-normal montserrat leading-loose tracking-normal">
							<TextMask>
								{[
									"Ranging between 4.2 to 14 gauss, the dynamic field is generated by eddying currents of conducting materials that circulate within the liquid metallic hydrogen core. Due to the planet having a huge magnetosphere that interacts with charged electromagnetic particles from the solar wind and ionosphere, it cooks up an electromagnetic vibrational soup that translates into sound waves and radio emissions, actually singing out a Jupiterian song for the cosmos to hear.",
								]}
							</TextMask>
						</p>
						<p className="text-black paragraph font-normal montserrat leading-loose tracking-normal">
							<TextMask>
								{[
									"Jupiter takes about twelve years to complete a circuit of the zodiac, spending about one year in each of the twelve signs. The station going retrograde or direct lasts from five to nine days wherein the planet appears motionless in the heavens as seen from earth. The retrograde period or apparent backwards motion lasts for around four months of each year, during which time payments or progress forward on projects may be delayed, although money may be made from prospects cultivated in the past. Sentiments tend to turn more conservative and the mind turns inwards, more naturally inclined to contemplation, study or a change in perspective. Keywords for Jupiter include masculine, warm, moist, electric and fruitful.",
								]}
							</TextMask>
						</p>
						<p className="text-black paragraph font-normal montserrat leading-loose tracking-normal">
							<TextMask>
								{[
									"In astrology, Jupiter is ruler of Sagittarius and traditional ruler of Pisces, therefore natural ruler of the ninth and twelfth houses of a horoscope. The planet is exalted in Cancer, in detriment in Gemini and Virgo and in fall in Capricorn. Detriment in this case can be associated with too many ideas or chatter, not enough substance in Gemini, overly righteous, busy-worked or obsessive-compulsive in Virgo. Jupiter in Capricorn can still enjoy some good luck, it is just channeled in a more conservative and hidebound way, all the way into abuse of authority. Jupiter is anciently associated with principles of expansion, abundance and generosity, good luck, prosperity and jolly good times.",
								]}
							</TextMask>
						</p>
						<p className="text-black paragraph font-normal montserrat leading-loose tracking-normal">
							<TextMask>
								{[
									"By transit Jupiter is useful as a financial indicator for investment, asset purchase or speculation as is Venus, however the two coupled by aspect is considered 'too much of a good thing' by Vedic astrologers and is prone to lead to a downfall. The Jovian spirit also represents the archetypes of benevolent authority and belief systems, especially those associated with kingship, organized religion and morality. It has been a traditional planetary symbol for the King of the Gods in the mental realms down on earth for a long time, whereas Saturn often holds the scepter for material authority. Both are considered as collective social arbiters, however Jupiter expands while Saturn contracts; both can traffic in dogma and the adroit use of it to condition, govern and control.",
								]}
							</TextMask>
						</p>
						<p className="text-black paragraph font-normal montserrat leading-loose tracking-normal">
							<TextMask>
								{[
									"Jupiter frequencies associate with higher education, entrepreneurship, publishing, philosophy, theology and jurisprudence. They also support the abstract mind and the search for truth, however one can be swayed into strange permutations around relative and absolute versions of the truth, or your truth versus my truth, and the convenient truth. In terms of health Jupiter holds overall rulership of the blood, arteries and arterial circulation. With Neptune it rules the hips, thighs, feet, liver and hepatic system, and supports the general glandular system along with the Sun. In nativities it is a prominent indicator for sugar disorders when teamed in any way with Venus, inflammatory conditions when teamed with Mars and emotional volatility when teamed with Uranus.",
								]}
							</TextMask>
						</p>
						<p className="text-black paragraph font-normal montserrat leading-loose tracking-normal">
							<TextMask>
								{[
									"The flip side of all that beneficence mentioned earlier can feature exaggeration, inflation and excessiveness, including obesity, gluttony and extravagance. Under a major Jupiter transit one may come to expect a turn of good fortune, but do be aware that the King of the Gods generally demands a sacrifice, fresh burden of responsibility or toil of some kind in return, there is no free lunch in the long run. Depending on the culture, Jupiterian authority is benevolent only as long as the rules are followed; departing from custom in favor of more individualistic forms of freedom will not generally not be rewarded, or rather one has to build a whole new relation to Jupiter’s physics.",
								]}
							</TextMask>
						</p>
						<p className="text-black paragraph font-normal montserrat leading-loose tracking-normal">
							<TextMask>
								{[
									"The position of Jupiter in a birth chart figures particularly in defining the native’s conditioned state and relationship to belief systems, including their use of them or abuse by them: For example, someone born with Jupiter in the seventh house will tend to partner with the belief systems of important others, instead of hewing to one’s own authentic creed. However someone born with Jupiter in the ninth house may make an ongoing life project of deploying belief systems as a utility, selecting one and holding on to it with great passion until disillusionment strikes or there is no further monetary or social use to get from it, wherein another belief system will be embraced and put into motion. It seems these days many individuals are not aware that belief systems are certainly compromising their own subconscious operating system, while others do not care to entertain a cogent set of personal values either. A healthy ego needs a sturdy working set of both, however there is a tremendous difference between an array that resonates with the requirements of higher self, and a block of do's and don'ts simply hammered into place by ancestral fiat or institutional decree.",
								]}
							</TextMask>
						</p>
					</div>
					<div className="w-full flex flex-col gap-4">
						<div className="w-full">
							<p className="text-black paragraph font-medium montserrat leading-loose tracking-normal">
								<TextMask>
									{[
										"We all need a good regular dose of Jupiterian optimism and inspiration though, to buoy progress forward through the jungle that is life on the earthly plane; and indeed it seems Lady Luck does favor those who can stay upbeat and open to fresh opportunity, more often than those who do not.",
									]}
								</TextMask>
							</p>
						</div>
						<div className="w-full">
							<p className="text-black paragraph font-normal montserrat leading-loose tracking-normal">
								<TextMask>
									{[
										"Tarot Cards: Emperor, Wheel of Fortune.",
										"Sepharoth: Chesed, the Cohesive or Receptacular Intelligence.",
										"Divine Name: El.",
										"Divine Symbol: Pyramidal Tetrahedron.",
										"Gods/Goddesses: Zeus, Isis, Amon-Ra, Juno, Brigit, Marduck, Thor, Brihaspati/Guru.",
										"Planetary Angels: Sachiel, Tzadquiel, Chasmalim.",
										"Stone: Ruby, amethyst, lapis lazuli.",
										"Key Sounds: E (659.255 Hz); G (391.996 Hz); D (587.330 Hz); A# (466.164 Hz).",
										"Colors: Violet, scarlet, bright blue, rayed yellow.",
									]}
								</TextMask>
							</p>
						</div>
					</div>
				</div>
			</div>
		</div>
	);
}
