export { default as fromImage } from './img.png';
export { default as placeholder } from './placeholder.png';
export { default as logo } from './logo.png';
export { default as heroBg } from './heroBg.png';
export { default as circle1 } from './circle1.png';
export { default as circle2 } from './circle2.png';
export { default as star } from './star.svg';
export { default as footerLogo } from './footerLogo.png';
export { default as service1 } from './service1.png';
export { default as service2 } from './service2.png';
export { default as service3 } from './service3.png';
export { default as brownStar } from './brownStar.svg';
export { default as formBg } from './formBg.png';
export { default as gradientCircle } from './gradientCircle.png';
export { default as testimonialsBg } from './testimonialsBg.png';
export { default as eyes } from './eyesvg.svg';
export { default as arrowGo } from './arrowGo.png';
export { default as arrowLeft } from './arrowLeft.png';
export { default as arrowRight } from './arrowRight.png';
export { default as client01 } from './client01.png';
export { default as client02 } from './client02.png';
export { default as client03 } from './client03.png';
export { default as client04 } from './client04.png';
export { default as videoThumbnail } from './videoThumbnail.png';
export { default as article01 } from './article01.png';
export { default as article02 } from './article02.png';
export { default as article03 } from './article03.png';
export { default as cardBack } from './card back.png';

export { default as Aquarius } from './Aquarius.png';
export { default as Aries } from './Aries.png';
export { default as Cancer } from './Cancer.png';
export { default as Capricorn } from './Capricorn.png';
export { default as Gemini } from './Gemini.png';
export { default as Leo } from './Leo.png';
export { default as Libra } from './Libra.png';
export { default as Pisces } from './Pisces.png';
export { default as Sagittarius } from './Sagittarius.png';
export { default as Scorpio } from './Scorpio.png';
export { default as Taurus } from './Taurus.png';
export { default as Virgo } from './Virgo.png';

export { default as cardAries } from './card aries.png';
export { default as cardCancer } from './card cancer.png';
export { default as cardGemini } from './card gemini.png';
export { default as cardLeo } from './card leo.png';
export { default as cardLibra } from './card libra.png';
export { default as cardAaurus } from './card taurus.png';
export { default as cardVirgo } from './card virgo.png';

export { default as introVideo } from './intro.mp4';
export { default as introVideo2 } from './intro2.mp4';