export { default as fromImage } from './img.jpg';
export { default as placeholder } from './placeholder.png';
export { default as logo } from './logo.png';
export { default as heroBg } from './heroBg.png';
export { default as circle1 } from './circle1.png';
export { default as circle2 } from './circle2.png';
export { default as star } from './star.svg';
export { default as footerLogo } from './footerLogo.png';
export { default as service1 } from './service1.png';
export { default as service2 } from './service2.png';
export { default as service3 } from './service3.png';
export { default as brownStar } from './brownStar.svg';
export { default as formBg } from './formBg.png';
export { default as gradientCircle } from './gradientCircle.png';
export { default as testimonialsBg } from './testimonialsBg.png';
export { default as eyes } from './eyesvg.svg';
export { default as arrowGo } from './arrowGo.png';
export { default as arrowLeft } from './arrowLeft.png';
export { default as arrowRight } from './arrowRight.png';
export { default as client01 } from './client01.png';
export { default as client02 } from './client02.png';
export { default as client03 } from './client03.png';
export { default as client04 } from './client04.png';
export { default as videoThumbnail } from './videoThumbnail.png';
export { default as article01 } from './article01.png';
export { default as article02 } from './article02.png';
export { default as article03 } from './article03.png';
export { default as cardBack } from './card back.png';

export { default as Aquarius } from './Aquarius.png';
export { default as Aries } from './Aries.png';
export { default as Cancer } from './Cancer.png';
export { default as Capricorn } from './Capricorn.png';
export { default as Gemini } from './Gemini.png';
export { default as Leo } from './Leo.png';
export { default as Libra } from './Libra.png';
export { default as Pisces } from './Pisces.png';
export { default as Sagittarius } from './Sagittarius.png';
export { default as Scorpio } from './Scorpio.png';
export { default as Taurus } from './Taurus.png';
export { default as Virgo } from './Virgo.png';

export { default as cardAries } from './card aries.png';
export { default as cardCancer } from './card cancer.png';
export { default as cardGemini } from './card gemini.png';
export { default as cardLeo } from './card leo.png';
export { default as cardLibra } from './card libra.png';
export { default as cardAaurus } from './card taurus.png';
export { default as cardVirgo } from './card virgo.png';

export { default as introVideo } from './intro.mp4';
export { default as introVideo2 } from './intro2.mp4';


export { default as about01 } from './about01.png';
export { default as about02 } from './about02.png';
export { default as planetry01 } from './planetry01.png';
export { default as planetry02 } from './planetry02.png';
export { default as planetry03 } from './planetry03.png';
export { default as planetry04 } from './planetry04.png';
export { default as planetry05 } from './planetry05.png';
export { default as planetry06 } from './planetry06.png';
export { default as planetry07 } from './planetry07.png';
export { default as planetry08 } from './planetry08.png';
export { default as planetry09 } from './planetry09.png';
export { default as planetry10 } from './planetry10.png';
export { default as planetry11 } from './planetry11.png';
export { default as planetry12 } from './planetry12.png';

export { default as blog01 } from './blog01.png';
export { default as blog02 } from './blog02.png';
export { default as blog03 } from './blog03.png';
export { default as blog04 } from './blog04.png';
export { default as blog05 } from './blog05.png';
export { default as blog06 } from './blog06.png';
export { default as blog07 } from './blog07.png';
export { default as blog08 } from './blog08.png';
export { default as blog09 } from './blog9.png';
export { default as blog10 } from './blog10.png';
export { default as blog11 } from './blog11.png';
export { default as blog12 } from './blog12.png';
export { default as comment01 } from './comment01.png';
export { default as comment02 } from './comment02.png';

export { default as star01 } from './star01.png';
export { default as star02 } from './star02.png';
export { default as star03 } from './star03.png';
export { default as star04 } from './star04.png';
export { default as star05 } from './star05.png';
export { default as star06 } from './star06.png';
export { default as star07 } from './star07.png';
export { default as star08 } from './star08.png';
export { default as star09 } from './star09.png';
export { default as star10 } from './star10.png';
export { default as arrowRight1 } from './arrowRight1.png';
export { default as arrowLeft1 } from './arrowLeft1.png';

export { default as plan01 } from './plan01.png';
export { default as plan02 } from './plan02.png';
export { default as plan03 } from './plan03.png';
export { default as plan04 } from './plan04.png';
export { default as plan05 } from './plan05.png';
export { default as plan06 } from './plan06.png';
export { default as plan07 } from './plan07.png';
export { default as plan08 } from './plan08.png';
export { default as plan09 } from './plan09.png';
export { default as plan10 } from './plan10.png';
export { default as plan11 } from './plan11.png';
export { default as plan12 } from './plan12.png';

export { default as life01 } from './life01.jpg';
export { default as life011 } from './life011.jpg';
export { default as life012 } from './life012.jpg';
export { default as life013 } from './life013.jpg';
export { default as life02 } from './life02.png';
export { default as life021 } from './life021.jpg';
export { default as life022 } from './life022.jpg';
export { default as life023 } from './life023.jpg';
export { default as life03 } from './life03.png';
export { default as life031 } from './life031.png';
export { default as life032 } from './life032.png';
export { default as life04 } from './life04.gif';
